name: dialog_loader
description: An easy way to create a loader, you can easily combine the loader with popular state management.
version: 0.0.3+1
homepage: https://github.com/sud0su/dialog_loader

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
